/**
 * FROZEN primitive schemas shared by every entity and API shape.
 *
 * Money and rates travel as decimal strings, never JSON numbers (D-010). Engines use decimal.js.
 */
import { z } from 'zod';
import { MoneyMeasure, MEASURE_TIME_BASIS, TimeBasis } from './enums';

/** UUID (v7 generated by the API; any RFC 4122 UUID accepted on input). */
export const Id = z.string().uuid();
export type Id = z.infer<typeof Id>;

/** Human-readable per-tenant keys. Format: PREFIX-NUMBER, e.g. ME-104, OPP-07, EXP-03, SRC-014, MD-21. */
export const DisplayKey = z
  .string()
  .regex(/^[A-Z]{1,5}(-[A-Z0-9]{1,6})+$/, 'Display key like ME-104 or ME-104-X1');
export type DisplayKey = z.infer<typeof DisplayKey>;

export const DISPLAY_KEY_PREFIXES = {
  case: 'ME',
  mandate: 'MD',
  opportunity: 'OPP',
  experiment: 'EXP',
  source: 'SRC',
  assumption: 'ASM',
  condition: 'C',
  comparison: 'CMP',
} as const;

export const IsoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, 'ISO date YYYY-MM-DD');
export type IsoDate = z.infer<typeof IsoDate>;

export const IsoDateTime = z.string().datetime({ offset: true });
export type IsoDateTime = z.infer<typeof IsoDateTime>;

/** Signed decimal as a string. Up to 18 integer digits and 8 fraction digits. */
export const DecimalString = z
  .string()
  .regex(/^-?\d{1,18}(\.\d{1,8})?$/, 'Decimal string such as "40000000.00" or "0.20"');
export type DecimalString = z.infer<typeof DecimalString>;

/** A fraction in [0, 1] as a decimal string. 20% adoption is "0.20". Never a confidence score. */
export const RateString = DecimalString.refine(
  (v) => Number(v) >= 0 && Number(v) <= 1,
  'Rate must be in [0, 1]',
);
export type RateString = z.infer<typeof RateString>;

export const CurrencyCode = z.string().regex(/^[A-Z]{3}$/, 'ISO 4217 code such as EUR');
export type CurrencyCode = z.infer<typeof CurrencyCode>;

export const PriceYear = z.number().int().min(2000).max(2100);
export type PriceYear = z.infer<typeof PriceYear>;

export const CountryCode = z.string().regex(/^[A-Z]{2}$/, 'ISO 3166-1 alpha-2 code such as DE');
export type CountryCode = z.infer<typeof CountryCode>;

/** Non-negative integer count (sites, customers, interviews). */
export const Count = z.number().int().nonnegative();
export type Count = z.infer<typeof Count>;

/** Signed integer count, used for signed adjustments such as "Overlap removed −500". */
export const SignedCount = z.number().int();
export type SignedCount = z.infer<typeof SignedCount>;

/** SHA-256 hex digest (64 lowercase hex chars). */
export const Sha256Hex = z.string().regex(/^[0-9a-f]{64}$/);
export type Sha256Hex = z.infer<typeof Sha256Hex>;

/** Display fingerprint: first 8 hex chars, uppercase, grouped "7F3A·19C2". Derived from Sha256Hex. */
export const Fingerprint = z.string().regex(/^[0-9A-F]{4}·[0-9A-F]{4}$/);
export type Fingerprint = z.infer<typeof Fingerprint>;

/**
 * Typed money. `measure` decides `timeBasis`; the pair is validated so a one-time amount can never
 * be labelled per-year. Missing money is represented by `Unavailable`, never by zero.
 */
export const Money = z
  .object({
    amount: DecimalString,
    currency: CurrencyCode,
    measure: MoneyMeasure,
    timeBasis: TimeBasis,
    priceYear: PriceYear.optional(),
  })
  .refine((m) => MEASURE_TIME_BASIS[m.measure] === m.timeBasis, {
    message: 'timeBasis must match the measure (recurring vs one-time are never mixed)',
    path: ['timeBasis'],
  });
export type Money = z.infer<typeof Money>;

/** A value that is required but not available. Rendered as "Not available — reason", never as 0. */
export const Unavailable = z.object({
  unavailable: z.literal(true),
  reason: z.string().min(1),
  missingInputs: z.array(z.string()).default([]),
});
export type Unavailable = z.infer<typeof Unavailable>;

export const MoneyOrUnavailable = z.union([Money, Unavailable]);
export type MoneyOrUnavailable = z.infer<typeof MoneyOrUnavailable>;

/** Reference to a person, as rendered in owner pickers and avatars. */
export const PersonRef = z.object({
  id: Id,
  displayName: z.string(),
  title: z.string().nullable(),
  initials: z.string().max(3),
});
export type PersonRef = z.infer<typeof PersonRef>;

/** Text that AI may draft. Human edits are never overwritten by regeneration (PRD §8). */
export const ProvenancedText = z.object({
  value: z.string(),
  origin: z.enum(['human', 'ai', 'ai_edited']),
  agentRunId: Id.nullable().default(null),
  editedBy: Id.nullable().default(null),
});
export type ProvenancedText = z.infer<typeof ProvenancedText>;

/** Audit stamp on every row. */
export const Stamp = z.object({
  createdAt: IsoDateTime,
  createdBy: Id,
  updatedAt: IsoDateTime.optional(),
  updatedBy: Id.optional(),
});
export type Stamp = z.infer<typeof Stamp>;

/** Optimistic concurrency token. Sent as ETag and checked with If-Match on draft writes. */
export const RowVersion = z.number().int().nonnegative();
export type RowVersion = z.infer<typeof RowVersion>;

/** Reference to an immutable versioned object. */
export const VersionRef = z.object({
  id: Id,
  version: z.number().int().positive(),
});
export type VersionRef = z.infer<typeof VersionRef>;

/** Format a SHA-256 hex digest as the display fingerprint, e.g. "7F3A·19C2". */
export function toFingerprint(hash: string): Fingerprint {
  const h = hash.slice(0, 8).toUpperCase();
  return `${h.slice(0, 4)}·${h.slice(4, 8)}`;
}
