/** FROZEN endpoints: mandates (S02), opportunities (S03), comparison (S04), case creation. */
import { z } from 'zod';
import { OpportunityStatus } from '../enums';
import { Page, PageQuery } from '../http';
import {
  Comparison,
  Mandate,
  MandateDraftFields,
  Opportunity,
  RankingRow,
  WorkflowCase,
} from '../entities/case';
import { GateRequest } from '../entities/gate';
import { Id } from '../primitives';
import { endpoint, IdParams, Ref, RefParams } from './endpoint';

export const mandateEndpoints = {
  list: endpoint({
    id: 'mandates.list',
    method: 'GET',
    path: '/me/mandates',
    summary: 'Mandates the viewer can access.',
    screens: ['S02'],
    prd: ['ME-01'],
    query: PageQuery,
    response: Page(Mandate),
  }),
  create: endpoint({
    id: 'mandates.create',
    method: 'POST',
    path: '/me/mandates',
    summary: 'Create a mandate with an empty draft version (Draft mandate).',
    screens: ['S01', 'S02'],
    prd: ['ME-01'],
    idempotent: true,
    body: z.object({ businessUnitId: Id, title: z.string().min(1), fields: MandateDraftFields }),
    response: Mandate,
  }),
  get: endpoint({
    id: 'mandates.get',
    method: 'GET',
    path: '/me/mandates/:ref',
    summary: 'Mandate with current and draft versions, live scope preview and validation errors.',
    screens: ['S02', 'S03'],
    prd: ['ME-01'],
    params: RefParams,
    response: Mandate,
  }),
  saveDraft: endpoint({
    id: 'mandates.saveDraft',
    method: 'PATCH',
    path: '/me/mandates/:ref/draft',
    summary: 'Autosave the draft. Partial fields allowed. Returns new ETag.',
    screens: ['S02'],
    prd: ['ME-01'],
    ifMatch: true,
    params: RefParams,
    body: z.object({ fields: MandateDraftFields }),
    response: Mandate,
  }),
  submit: endpoint({
    id: 'mandates.submitForG0',
    method: 'POST',
    path: '/me/mandates/:ref/submit',
    summary:
      'Validate required fields (owner, currency, compatible horizons), commit the version and open the G0 gate request with a snapshot.',
    screens: ['S02'],
    prd: ['ME-01', 'ME-10'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    response: z.object({ mandate: Mandate, gateRequest: GateRequest }),
  }),
};

export const opportunityEndpoints = {
  list: endpoint({
    id: 'opportunities.list',
    method: 'GET',
    path: '/me/opportunities',
    summary:
      'Candidates for a mandate with filters. Includes a partial-discovery flag when a source is unavailable.',
    screens: ['S03'],
    prd: ['ME-03'],
    query: PageQuery.extend({
      mandateId: Id,
      status: OpportunityStatus.optional(),
      productId: Id.optional(),
      countryCode: z.string().optional(),
      segmentId: Id.optional(),
    }),
    response: Page(Opportunity).extend({
      discoveryPartial: z.boolean(),
      unavailableSources: z.array(z.object({ connectionId: Id, name: z.string(), since: z.string() })),
      filtersText: z.string(),
    }),
  }),
  get: endpoint({
    id: 'opportunities.get',
    method: 'GET',
    path: '/me/opportunities/:ref',
    summary: 'One candidate with fit criteria, evidence, unknowns and duplicate hint.',
    screens: ['S03'],
    prd: ['ME-03'],
    params: RefParams,
    response: Opportunity,
  }),
  createManual: endpoint({
    id: 'opportunities.createManual',
    method: 'POST',
    path: '/me/opportunities',
    summary: 'Add a candidate manually. Starts as Detected with no evidence.',
    screens: ['S03'],
    prd: ['ME-03'],
    idempotent: true,
    body: z.object({
      mandateId: Id,
      name: z.string().min(1),
      trigger: z.string().default(''),
      fitRationale: z.string().default(''),
    }),
    response: Opportunity,
  }),
  shortlist: endpoint({
    id: 'opportunities.shortlist',
    method: 'POST',
    path: '/me/opportunities/:ref/shortlist',
    summary: 'Detected → Shortlisted.',
    screens: ['S03'],
    prd: ['ME-03'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    response: Opportunity,
    successStatus: 200,
  }),
  dismiss: endpoint({
    id: 'opportunities.dismiss',
    method: 'POST',
    path: '/me/opportunities/:ref/dismiss',
    summary: 'Dismiss with a required reason. Stays visible under the Dismissed filter.',
    screens: ['S03'],
    prd: ['ME-03'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ reason: z.string().min(1) }),
    response: Opportunity,
    successStatus: 200,
  }),
  merge: endpoint({
    id: 'opportunities.merge',
    method: 'POST',
    path: '/me/opportunities/:ref/merge',
    summary: 'Mark as Duplicate of a target. Both records are kept and linked.',
    screens: ['S03'],
    prd: ['ME-03'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ targetOpportunityId: Id }),
    response: z.object({ merged: Opportunity, target: Opportunity }),
    successStatus: 200,
  }),
  restore: endpoint({
    id: 'opportunities.restore',
    method: 'POST',
    path: '/me/opportunities/:ref/restore',
    summary: 'Dismissed → Detected with a reason.',
    screens: ['S03'],
    prd: ['ME-03'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ reason: z.string().min(1) }),
    response: Opportunity,
    successStatus: 200,
  }),
  convert: endpoint({
    id: 'opportunities.convertToCase',
    method: 'POST',
    path: '/me/opportunities/:ref/convert',
    summary:
      'Shortlisted → Converted. Creates an expansion case in Discovery (mandate must be G0-approved). Keeps evidence and origin.',
    screens: ['S03', 'S04'],
    prd: ['ME-03', 'ME-01'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ ownerId: Id }),
    response: z.object({ opportunity: Opportunity, case: WorkflowCase }),
  }),
  requestDiscovery: endpoint({
    id: 'opportunities.requestDiscovery',
    method: 'POST',
    path: '/me/mandates/:ref/discovery-runs',
    summary:
      'Start a bounded analysis run (mandate-to-search-plan) that proposes candidates. Results stay "Proposed · AI".',
    screens: ['S03'],
    prd: ['ME-03', 'ME-02'],
    idempotent: true,
    params: RefParams,
    response: z.object({ runId: Id }),
    successStatus: 202,
  }),
};

export const comparisonEndpoints = {
  create: endpoint({
    id: 'comparisons.create',
    method: 'POST',
    path: '/me/comparisons',
    summary: 'Compare up to four candidates on a common unit and horizon.',
    screens: ['S03', 'S04'],
    prd: ['ME-04'],
    idempotent: true,
    body: z.object({ mandateId: Id, opportunityRefs: z.array(Ref).min(2).max(4) }),
    response: Comparison,
  }),
  get: endpoint({
    id: 'comparisons.get',
    method: 'GET',
    path: '/me/comparisons/:id',
    summary: 'Comparison with cells (Unknown never 0), incomparable warnings, weights and ranking.',
    screens: ['S04'],
    prd: ['ME-04'],
    params: IdParams,
    response: Comparison,
  }),
  previewRanking: endpoint({
    id: 'comparisons.previewRanking',
    method: 'POST',
    path: '/me/comparisons/:id/ranking-preview',
    summary: 'Preview a weight change without applying it. Pure; writes nothing.',
    screens: ['S04'],
    prd: ['ME-04'],
    params: IdParams,
    body: z.object({
      productFit: z.number().int(),
      channelAccess: z.number().int(),
      evidenceCoverage: z.number().int(),
    }),
    response: z.object({ ranking: z.array(RankingRow), totalWeight: z.number().int(), valid: z.boolean() }),
    successStatus: 200,
  }),
  applyWeights: endpoint({
    id: 'comparisons.applyWeights',
    method: 'POST',
    path: '/me/comparisons/:id/weights',
    summary: 'Apply weights as a new version; earlier versions are kept.',
    screens: ['S04'],
    prd: ['ME-04'],
    idempotent: true,
    params: IdParams,
    body: z.object({
      productFit: z.number().int(),
      channelAccess: z.number().int(),
      evidenceCoverage: z.number().int(),
    }),
    response: Comparison,
  }),
  setExclusion: endpoint({
    id: 'comparisons.setExclusion',
    method: 'PUT',
    path: '/me/comparisons/:id/exclusions/:opportunityId',
    summary:
      'Exclude or include a candidate in the ranking (e.g. until its boundary is normalized). It stays in the table.',
    screens: ['S04'],
    prd: ['ME-04'],
    params: z.object({ id: Id, opportunityId: Id }),
    body: z.object({ excluded: z.boolean(), reason: z.string().nullable() }),
    response: Comparison,
  }),
  select: endpoint({
    id: 'comparisons.selectForAssessment',
    method: 'POST',
    path: '/me/comparisons/:id/select',
    summary: 'Select a candidate for assessment (shortlists it). Does not approve spend.',
    screens: ['S04'],
    prd: ['ME-04'],
    auth: 'human',
    idempotent: true,
    params: IdParams,
    body: z.object({ opportunityId: Id }),
    response: Comparison,
    successStatus: 200,
  }),
};
