/**
 * FROZEN endpoints: evidence (S13), analysis runs and proposals (S05 analysis strip, S03),
 * administration and diagnostics (S14), dev-only simulator controls.
 */
import { z } from 'zod';
import { EntitlementAccess, GateCode, RoleCode, SkillKey } from '../enums';
import { Challenge, Source, SourceDetail } from '../entities/evidence';
import { AnalysisRun, Proposal, RunStep, ToolCallRecord } from '../entities/analysis';
import { AuditEvent } from '../entities/audit';
import {
  AuthorityGrant,
  Connection,
  ConnectorMapping,
  GatePolicyBody,
  MaterialityPolicyBody,
  Policy,
  RoleAssignment,
  RunBudgetPolicyBody,
} from '../entities/platform';
import { Page, PageQuery } from '../http';
import { CurrencyCode, DecimalString, Id, IsoDate } from '../primitives';
import { CaseParams, endpoint, IdParams, RefParams } from './endpoint';

export const evidenceEndpoints = {
  list: endpoint({
    id: 'evidence.list',
    method: 'GET',
    path: '/evidence/sources',
    summary: 'Sources the viewer can see (metadata), optionally for one case.',
    screens: ['S13'],
    prd: ['ME-02', 'ME-16'],
    query: PageQuery.extend({ caseRef: z.string().optional() }),
    response: Page(Source),
  }),
  get: endpoint({
    id: 'evidence.get',
    method: 'GET',
    path: '/evidence/sources/:ref',
    summary:
      'Source detail with permitted excerpt only; restricted shows no excerpt, summary or paraphrase. Impact lists accessible cases only.',
    screens: ['S13'],
    prd: ['ME-02', 'ME-16', 'S13'],
    params: RefParams,
    response: SourceDetail,
  }),
  upload: endpoint({
    id: 'evidence.upload',
    method: 'POST',
    path: '/evidence/sources',
    summary: 'Register an authorized upload (multipart: metadata + file). Ingestion runs asynchronously.',
    screens: ['S13', 'S03', 'S06'],
    prd: ['ME-02'],
    idempotent: true,
    body: z.object({
      title: z.string().min(1),
      publisher: z.string().nullable(),
      publishedOn: IsoDate.nullable(),
      licenseId: Id,
      caseRef: z.string().nullable(),
      fileName: z.string(),
    }),
    response: Source,
    successStatus: 202,
  }),
  challenge: endpoint({
    id: 'evidence.challenge',
    method: 'POST',
    path: '/evidence/sources/:ref/challenges',
    summary: 'Challenge a source (required statement).',
    screens: ['S13'],
    prd: ['ME-15'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ statement: z.string().min(1) }),
    response: Challenge,
  }),
  markStale: endpoint({
    id: 'evidence.markStale',
    method: 'POST',
    path: '/evidence/sources/:ref/stale',
    summary: 'Mark stale with a reason. Runs the materiality check for snapshots that use it.',
    screens: ['S13'],
    prd: ['ME-15', 'ME-20'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ reason: z.string().min(1) }),
    response: SourceDetail,
    successStatus: 200,
  }),
  replace: endpoint({
    id: 'evidence.replace',
    method: 'POST',
    path: '/evidence/sources/:ref/replace',
    summary:
      'Replace with a newer source. Re-links claims in drafts only; approved snapshots keep the original.',
    screens: ['S13'],
    prd: ['ME-15'],
    auth: 'human',
    idempotent: true,
    params: RefParams,
    body: z.object({ replacementSourceId: Id }),
    response: SourceDetail,
    successStatus: 200,
  }),
  requestAccess: endpoint({
    id: 'evidence.requestAccess',
    method: 'POST',
    path: '/evidence/sources/:ref/access-requests',
    summary: 'Ask the licence owner for access. Reveals nothing.',
    screens: ['S13', 'S06'],
    prd: ['ME-16'],
    idempotent: true,
    params: RefParams,
    body: z.object({ reason: z.string().min(1) }),
    response: z.object({ requested: z.literal(true) }),
  }),
};

export const analysisEndpoints = {
  start: endpoint({
    id: 'analysis.start',
    method: 'POST',
    path: '/me/cases/:caseRef/analysis-runs',
    summary: 'Request analysis with a skill. Immediate acknowledgement; runs asynchronously within budget.',
    screens: ['S05', 'S06', 'S07', 'S08', 'S09', 'S11', 'S12'],
    prd: ['§8', 'ME-15'],
    idempotent: true,
    params: CaseParams,
    body: z.object({
      skill: SkillKey,
      goal: z.string().min(1),
      focus: z.record(z.string(), z.string()).default({}),
    }),
    response: AnalysisRun,
    successStatus: 202,
  }),
  get: endpoint({
    id: 'analysis.get',
    method: 'GET',
    path: '/me/analysis-runs/:id',
    summary: 'Run status for the analysis strip (poll while queued/running).',
    screens: ['S05', 'S03'],
    prd: ['§8'],
    params: IdParams,
    response: z.object({ run: AnalysisRun, steps: z.array(RunStep) }),
  }),
  latestForCase: endpoint({
    id: 'analysis.latestForCase',
    method: 'GET',
    path: '/me/cases/:caseRef/analysis-runs',
    summary: 'Recent runs for a case.',
    screens: ['S05'],
    prd: ['§8'],
    params: CaseParams,
    query: PageQuery,
    response: Page(AnalysisRun),
  }),
  cancel: endpoint({
    id: 'analysis.cancel',
    method: 'POST',
    path: '/me/analysis-runs/:id/cancel',
    summary: 'Cancel. Committed results and human edits are kept.',
    screens: ['S05'],
    prd: ['§8'],
    idempotent: true,
    params: IdParams,
    response: AnalysisRun,
    successStatus: 200,
  }),
  resume: endpoint({
    id: 'analysis.resume',
    method: 'POST',
    path: '/me/analysis-runs/:id/resume',
    summary: 'Resume a partial/failed run from its last checkpoint.',
    screens: ['S05'],
    prd: ['§8'],
    idempotent: true,
    params: IdParams,
    response: AnalysisRun,
    successStatus: 202,
  }),
  provideInput: endpoint({
    id: 'analysis.provideInput',
    method: 'POST',
    path: '/me/analysis-runs/:id/input',
    summary: 'Answer a "Needs your input" question.',
    screens: ['S05'],
    prd: ['§8'],
    idempotent: true,
    params: IdParams,
    body: z.object({ answer: z.string().min(1) }),
    response: AnalysisRun,
    successStatus: 202,
  }),
  proposals: endpoint({
    id: 'analysis.proposals',
    method: 'GET',
    path: '/me/cases/:caseRef/proposals',
    summary: 'Pending AI proposals for a case.',
    screens: ['S05', 'S03', 'S06', 'S09', 'S11', 'S12'],
    prd: ['§8', 'ME-15'],
    params: CaseParams,
    query: z.object({ status: z.enum(['proposed', 'accepted', 'rejected']).optional() }),
    response: z.object({ items: z.array(Proposal) }),
  }),
  decideProposal: endpoint({
    id: 'analysis.decideProposal',
    method: 'POST',
    path: '/me/proposals/:id/decision',
    summary:
      'Accept (optionally edited) or reject a proposal. Accepting writes the business record with origin ai or ai_edited.',
    screens: ['S05', 'S03', 'S06', 'S09', 'S11', 'S12'],
    prd: ['§8', 'ME-15'],
    auth: 'human',
    idempotent: true,
    params: IdParams,
    body: z.object({
      decision: z.enum(['accept', 'reject']),
      editedPayload: z.unknown().optional(),
      reason: z.string().nullable(),
    }),
    response: Proposal,
    successStatus: 200,
  }),
};

export const adminEndpoints = {
  roles: endpoint({
    id: 'admin.roles',
    method: 'GET',
    path: '/admin/role-assignments',
    summary: 'Roles table (S14).',
    screens: ['S14'],
    prd: ['ME-16'],
    response: z.object({ items: z.array(RoleAssignment) }),
  }),
  setRole: endpoint({
    id: 'admin.setRole',
    method: 'PUT',
    path: '/admin/role-assignments/:id',
    summary: 'Grant or revoke a role. Admins configure but never gain approval authority.',
    screens: ['S14'],
    prd: ['ME-16', 'S14'],
    auth: 'human',
    idempotent: true,
    params: IdParams,
    body: z.object({
      userId: Id,
      role: RoleCode,
      businessUnitId: Id.nullable(),
      caseId: Id.nullable(),
      revoked: z.boolean(),
    }),
    response: RoleAssignment,
  }),
  authority: endpoint({
    id: 'admin.authority',
    method: 'GET',
    path: '/admin/authority-grants',
    summary: 'Delegated authority matrix (gate × BU × ceiling) and authority gaps.',
    screens: ['S14'],
    prd: ['ME-11', 'S14'],
    response: z.object({
      items: z.array(AuthorityGrant),
      gaps: z.array(z.object({ gateCode: GateCode, businessUnitId: Id, message: z.string() })),
    }),
  }),
  setAuthority: endpoint({
    id: 'admin.setAuthority',
    method: 'PUT',
    path: '/admin/authority-grants/:id',
    summary: 'Create/replace/revoke a grant. Grantee must not be a tenant admin acting for themselves.',
    screens: ['S14'],
    prd: ['ME-11'],
    auth: 'human',
    idempotent: true,
    params: IdParams,
    body: z.object({
      userId: Id,
      gateCode: GateCode,
      businessUnitId: Id,
      ceilingAmount: DecimalString.nullable(),
      currency: CurrencyCode.nullable(),
      validFrom: IsoDate,
      validTo: IsoDate.nullable(),
      revoked: z.boolean(),
    }),
    response: AuthorityGrant,
  }),
  policies: endpoint({
    id: 'admin.policies',
    method: 'GET',
    path: '/admin/policies',
    summary: 'Gate policies, materiality rule, approval expiry, retention, run budget (active versions).',
    screens: ['S14'],
    prd: ['§4', 'S14'],
    response: z.object({ items: z.array(Policy) }),
  }),
  publishPolicy: endpoint({
    id: 'admin.publishPolicy',
    method: 'POST',
    path: '/admin/policies',
    summary:
      'Publish a new policy version. Policies are versioned; old versions are kept. Cannot disable self-approval checks.',
    screens: ['S14'],
    prd: ['§4', 'S14'],
    auth: 'human',
    idempotent: true,
    body: z.discriminatedUnion('kind', [
      z.object({ kind: z.literal('gate'), key: z.string(), body: GatePolicyBody }),
      z.object({ kind: z.literal('materiality'), key: z.string(), body: MaterialityPolicyBody }),
      z.object({ kind: z.literal('run_budget'), key: z.string(), body: RunBudgetPolicyBody }),
      z.object({
        kind: z.literal('approval_expiry'),
        key: z.string(),
        body: z.object({ days: z.number().int().positive() }),
      }),
      z.object({
        kind: z.literal('retention'),
        key: z.string(),
        body: z.object({ approvalHistoryYears: z.number().int().positive().nullable(), note: z.string() }),
      }),
    ]),
    response: Policy,
  }),
  entitlements: endpoint({
    id: 'admin.entitlements',
    method: 'GET',
    path: '/admin/source-entitlements',
    summary: 'Licences and who sees excerpts / aggregates / nothing.',
    screens: ['S14'],
    prd: ['ME-16', 'ME-02'],
    response: z.object({
      items: z.array(
        z.object({
          licenseId: Id,
          sourceLabel: z.string(),
          licenseText: z.string(),
          excerptVisibleTo: z.array(z.string()),
          othersSee: EntitlementAccess,
        }),
      ),
    }),
  }),
  connections: endpoint({
    id: 'admin.connections',
    method: 'GET',
    path: '/admin/connections',
    summary: 'Connection health rows: status, scope, last success, used for.',
    screens: ['S14', 'S03', 'S11'],
    prd: ['ME-13', 'S14'],
    response: z.object({ items: z.array(Connection), mappings: z.array(ConnectorMapping) }),
  }),
  testConnection: endpoint({
    id: 'admin.testConnection',
    method: 'POST',
    path: '/admin/connections/:id/test',
    summary: 'Health check through the connector interface.',
    screens: ['S14'],
    prd: ['ME-13'],
    idempotent: true,
    params: IdParams,
    response: Connection,
    successStatus: 200,
  }),
  reconnect: endpoint({
    id: 'admin.reconnect',
    method: 'POST',
    path: '/admin/connections/:id/reconnect',
    summary: 'Re-authorize a connection (simulated in dev). Paused sync resumes only after re-check.',
    screens: ['S14', 'S11'],
    prd: ['ME-13'],
    auth: 'human',
    idempotent: true,
    params: IdParams,
    response: Connection,
    successStatus: 200,
  }),
  setMapping: endpoint({
    id: 'admin.setMapping',
    method: 'PUT',
    path: '/admin/connector-mappings/:id',
    summary: 'Destination project, issue type and assignee map.',
    screens: ['S14'],
    prd: ['ME-13'],
    auth: 'human',
    idempotent: true,
    params: IdParams,
    body: ConnectorMapping.omit({ id: true }),
    response: ConnectorMapping,
  }),
  runDiagnostics: endpoint({
    id: 'admin.runDiagnostics',
    method: 'GET',
    path: '/admin/diagnostics/runs/:id',
    summary: 'Admin-only trace: structured outputs and tool events, never hidden reasoning.',
    screens: ['S14'],
    prd: ['S14', '§13'],
    params: IdParams,
    response: z.object({ run: AnalysisRun, steps: z.array(RunStep), toolCalls: z.array(ToolCallRecord) }),
  }),
  audit: endpoint({
    id: 'admin.audit',
    method: 'GET',
    path: '/admin/audit',
    summary: 'Scoped audit search.',
    screens: ['S14'],
    prd: ['ME-17'],
    query: PageQuery.extend({
      caseId: Id.optional(),
      actorId: Id.optional(),
      action: z.string().optional(),
      from: z.string().optional(),
      to: z.string().optional(),
    }),
    response: Page(AuditEvent),
  }),
};

/** Dev/test only. Registered when AUTH_MODE=dev. Drives the simulated task connector. */
export const SimFaultRule = z.object({
  mode: z.enum(['timeout_after_success', 'http_5xx', 'permission_denied', 'token_expired', 'rate_limited']),
  match: z.object({
    titleContains: z.string().optional(),
    assignee: z.string().optional(),
    nthCall: z.number().int().positive().optional(),
  }),
  times: z.number().int().positive().default(1),
});
export type SimFaultRule = z.infer<typeof SimFaultRule>;

/**
 * Dev/test only (D-091). The tenant's business clock: real time plus a forward offset, honoured only
 * with AUTH_MODE=dev for illustrative tenants. Audit timestamps never use it.
 */
export const DevClock = z.object({
  /** Business "now" for this tenant (ISO date-time). */
  now: z.string(),
  /** Offset from real time in ms; 0 = real time. Moves forward only. */
  offsetMs: z.number().int().nonnegative(),
  setAt: z.string().nullable(),
});
export type DevClock = z.infer<typeof DevClock>;

export const devEndpoints = {
  clock: endpoint({
    id: 'dev.clock',
    method: 'GET',
    path: '/dev/clock',
    summary: "Read the tenant's dev clock (business time used by the API, timers and send-time checks).",
    screens: ['S14'],
    prd: ['§10'],
    auth: 'dev_only',
    response: DevClock,
  }),
  setClock: endpoint({
    id: 'dev.setClock',
    method: 'PUT',
    path: '/dev/clock',
    summary:
      'Move the dev clock forward to a moment (or by a number of days) and run the pilot-window and approval-expiry timers at once. Forward only; reseed to go back.',
    screens: ['S14'],
    prd: ['§10'],
    auth: 'dev_only',
    body: z
      .object({
        to: z.string().datetime({ offset: true }).optional(),
        advanceDays: z.number().int().positive().max(3650).optional(),
      })
      .refine((b) => (b.to === undefined) !== (b.advanceDays === undefined), {
        message: 'Give either `to` or `advanceDays`.',
      }),
    response: DevClock,
    successStatus: 200,
  }),

  setFaults: endpoint({
    id: 'dev.setConnectorFaults',
    method: 'PUT',
    path: '/dev/simulator/faults',
    summary: 'Configure fault injection on the simulated task connector.',
    screens: ['S14'],
    prd: ['ME-13', '§10'],
    auth: 'dev_only',
    body: z.object({ connectionId: Id, rules: z.array(SimFaultRule) }),
    response: z.object({ rules: z.array(SimFaultRule) }),
  }),
  simulatedIssues: endpoint({
    id: 'dev.simulatedIssues',
    method: 'GET',
    path: '/dev/simulator/issues',
    summary: 'Inspect issues in the simulated tool (used by duplicate-write tests).',
    screens: ['S14'],
    prd: ['ME-13'],
    auth: 'dev_only',
    query: z.object({ connectionId: Id }),
    response: z.object({
      items: z.array(
        z.object({
          key: z.string(),
          title: z.string(),
          idempotencyKey: z.string(),
          assignee: z.string().nullable(),
          createdAt: z.string(),
        }),
      ),
    }),
  }),
};
